language: cpp
sudo: false
matrix:
  include:

  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.5
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - python-numpy
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.5
        - libhdf5-serial-dev
        - gfortran
    env:
      - CXX_COMPILER='clang++-3.5'
      - C_COMPILER='clang-3.5'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.5'

  - os: linux
    compiler: clang
    addons: &2
      apt:
        sources:
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - python-numpy
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.8
        - libhdf5-serial-dev
        - gfortran
    env:
      - CXX_COMPILER='clang++-3.8'
      - C_COMPILER='clang-3.8'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.8'


  - os: linux
    compiler: gcc
    addons: &3
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - python-numpy
        - cmake
        - cmake-data
        - liblapack-dev
        - libhdf5-serial-dev
        - g++-4.8
        - gcc-4.8
        - gfortran-4.8
    env:
      - CXX_COMPILER='g++-4.8'
      - C_COMPILER='gcc-4.8'
      - Fortran_COMPILER='gfortran-4.8'
      - BUILD_TYPE='release'
      - NAME='gcc'
      - VERSION='4.8'

  - os: linux
    compiler: gcc
    addons: &4
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - python-numpy
        - cmake
        - cmake-data
        - libhdf5-serial-dev
        - liblapack-dev
        - g++-5
        - gcc-5
        - gfortran-5
    env:
      - CXX_COMPILER='g++-5'
      - C_COMPILER='gcc-5'
      - Fortran_COMPILER='gfortran-5'
      - BUILD_TYPE='release'
      - NAME='gcc'
      - VERSION=5
  - os: linux
    compiler: gcc
    addons: *4
    env:
      - CXX_COMPILER='g++-5'
      - C_COMPILER='gcc-5'
      - Fortran_COMPILER='gfortran-5'
      - BUILD_TYPE='debug'
      - NAME='gcc'
      - VERSION=5


before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew install cmake python
    brew install boost --with-python
    brew install boost-python
  fi
before_script:
- python -c 'import numpy; print numpy.version.version'
- cd ${TRAVIS_BUILD_DIR}
- export CXX=${CXX_COMPILER}
- export CC=${C_COMPILER}
- export FC=${Fortran_COMPILER}
- export CTEST_OUTPUT_ON_FAILURE=1
- export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/boost_install/lib:${LD_LIBRARY_PATH}
- ${CXX_COMPILER} --version
- ${Fortran_COMPILER} --version
- ${C_COMPILER} --version
- .scripts/build_boost.sh ${NAME} ${VERSION} ${CXX_COMPILER}
- > 
    cmake -Bbuild -H. 
    -DCMAKE_CXX_COMPILER=${CXX_COMPILER} 
    -DCMAKE_C_COMPILER=${C_COMPILER} 
    -DFortran_COMPILER=${Fortran_COMPILER} 
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
    -DLIBINT_OPT_AM=4 
    -DENABLE_CHEMPS2=off 
    -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/Install
    -DBOOST_ROOT=${TRAVIS_BUILD_DIR}/boost_install
- cd build
- ../.scripts/travis_build.sh
script:
- python ../.scripts/travis_run.py
